### ISSUE TITLE
Is there an example project that demonstrates usage?

### ISSUE THREAD

**Issue by dgwyer** [robbevp/postcss-multiple-tailwind#128]
Hi, thanks for creating this postcss plugin to allow you to use multiple tailwind configuration files.

I tried it in one of my own projects but it doesn't auto trigger recompilation of Tailwind styles when the source code is edited. I don't know if it is me doing something wrong or an issue with the postcss plugin.

Have you a simple project demonstrating usage of the plugin that I can use to verify how it works so I can try to figure out where I'm going wrong?

**Comment by robbevp** [comment]
I don't have an example repo on hand, sorry

Just to clarify:
What version of Tailwind / postcss you are using?
Are there any other tools in your built chain that might interfere?
Does Tailwind not recompile when you edit the css file or when you edit a file referenced in the `contents` of one of your configs?

**Comment by dgwyer** [comment]
I just created a test project here: https://github.com/dgwyer/multiple-tailwind-configs. To run the project:

```
npm i
npm start
```

Once running I found that editing the CSS source files recompiles the Tailwind classes. However, editing the JS source files does not. **This is the main issue**.

In `postcss.config.js` if you comment out the `postcss-multiple-tailwind` plugin and enable one of the tailwind plugins, then whenever any of the JS source files are edited then the Tailwind classes are compiled as expected.

So I'm thinking there may be a compatibility issue with the latest version of Tailwind which is 3.0.23 in this project? What do you think?

**Comment by dgwyer** [comment]
Thanks for the screencast. Yes, the webpack 'watch' triggers when you edit JS source files but the Tailwind compilation does not.

If you repeat the steps you did in the video but this time have open the compiled JS and CSS files as I have here in the editor:

![image](https://user-images.githubusercontent.com/1482075/159535231-9b6a60e9-5a93-4202-9aa3-027db7901379.png)

Now, if you edit (for example) `./src/block1/style1.css` you'll see the `./build/block1/index.css` Tailwind styles compile. However, if you edit `./src/block1/main1.js` even though the target JS file updates, the target CSS does not recompile Tailwind classes.

**Comment by robbevp** [comment]
hi @dgwyer 

I just published a new version of the plugin, and was able to confirm that everything now works in the example project you created.
Let me know if you bump into any other issues!

**Comment by dgwyer** [comment]
Just tested and can confirm it now works as expected. Thanks so much for this!

**Comment by robbevp** [comment]
Ah sorry, I misunderstood. I am able to reproduce the issue. Let me see if I can figure out what is going wrongOn 22 Mar 2022 18:06, David Gwyer ***@***.***> wrote:
Thanks for the screencast. Yes, the webpack 'watch' triggers when you edit JS source files but the Tailwind compilation does not.
If you repeat the steps you did in the video but this time have open the compiled JS and CSS files as I have here in the editor:

Now, if you edit (for example) ./src/block1/style1.css you'll see the ./build/block1/index.css Tailwind styles compile. However, if you edit ./src/block1/main1.js even though the target JS file updates, the target CSS does not recompile Tailwind classes.
